"""Deterministic CAM JSON -> LaTeX renderer."""

from __future__ import annotations

from typing import Any

from src.cam.latex_sanitizer import escape_latex
from src.cam.latex_template import get_latex_template


def _paragraph(text: object) -> str:
    return escape_latex(text) + "\n"


def _render_risk_flags(flags: list[dict[str, Any]]) -> str:
    if not flags:
        return r"\begin{itemize}\item No major risk flags identified.\end{itemize}" + "\n"
    out = [r"\begin{itemize}"]
    for f in flags:
        flag = escape_latex(f.get("flag", "Risk Flag"))
        exp = escape_latex(f.get("explanation", ""))
        out.append(rf"\item \textbf{{{flag}}}: {exp}")
    out.append(r"\end{itemize}")
    return "\n".join(out) + "\n"


def _render_conditions(conditions: list[object]) -> str:
    if not conditions:
        return _paragraph("No additional covenants were generated by the current policy rules.")
    out = [r"\begin{itemize}"]
    for c in conditions[:12]:
        out.append(rf"\item {escape_latex(c)}")
    out.append(r"\end{itemize}")
    return "\n".join(out) + "\n"


def _render_evidence(evidence: list[dict[str, Any]]) -> str:
    if not evidence:
        return r"\begin{itemize}\item No supporting evidence snippets retrieved.\end{itemize}" + "\n"
    out = [r"\begin{itemize}"]
    for ev in evidence:
        src = escape_latex(ev.get("source", "unknown"))
        ref = escape_latex(ev.get("reference", ""))
        excerpt = escape_latex(ev.get("excerpt", ""))
        if ref:
            out.append(rf"\item \textbf{{Source:}} {src} ({ref}) \\ \textit{{Excerpt:}} {excerpt}")
        else:
            out.append(rf"\item \textbf{{Source:}} {src} \\ \textit{{Excerpt:}} {excerpt}")
    out.append(r"\end{itemize}")
    return "\n".join(out) + "\n"


def _render_table(table: dict[str, Any]) -> str:
    headers = [escape_latex(h) for h in table.get("headers", [])]
    rows = table.get("rows", [])
    if not headers:
        return escape_latex("Financial table unavailable.") + "\n"

    col_count = len(headers)
    col_spec = "p{3.2cm} " + " ".join(["p{1.8cm}"] * (col_count - 1))

    out = [
        r"\begin{longtable}{" + col_spec + "}",
        r"\toprule",
        " & ".join(headers) + r" \\",
        r"\midrule",
        r"\endhead",
    ]
    for row in rows:
        cells = [escape_latex(c) for c in row]
        # Pad/trim for safety.
        if len(cells) < col_count:
            cells.extend([""] * (col_count - len(cells)))
        elif len(cells) > col_count:
            cells = cells[:col_count]
        out.append(" & ".join(cells) + r" \\")
    out.extend([r"\bottomrule", r"\end{longtable}"])
    return "\n".join(out) + "\n"


def _render_kv_table(rows: list[tuple[str, object]]) -> str:
    if not rows:
        return ""
    safe_rows = [(escape_latex(k), escape_latex(v)) for k, v in rows]
    out = [
        r"\begin{longtable}{p{5.0cm} p{9.5cm}}",
        r"\toprule",
        r"\textbf{Field} & \textbf{Value} \\",
        r"\midrule",
        r"\endhead",
    ]
    for k, v in safe_rows:
        out.append(rf"{k} & {v} \\")
    out.extend([r"\bottomrule", r"\end{longtable}"])
    return "\n".join(out) + "\n"


def _fmt_pct(value: object) -> str:
    try:
        return f"{float(value):.2f}%"
    except Exception:
        return "NA"


def _fmt_crore(value: object) -> str:
    try:
        return f"INR {float(value):,.2f} Crores"
    except Exception:
        return "NA"


def _render_schema_mapping(schema_map: dict[str, Any]) -> str:
    mappings = schema_map.get("mappings", {}) if isinstance(schema_map.get("mappings"), dict) else {}
    if not mappings:
        return _paragraph("Schema mapping not available.")
    rows = []
    for doc_type, fields in list(mappings.items())[:20]:
        field_list = ", ".join(str(x) for x in (fields or []))
        rows.append((str(doc_type).replace("_", " ").title(), field_list if field_list else "No fields configured"))
    return _render_kv_table(rows)


def _render_extraction_summary(extracted: dict[str, Any]) -> str:
    data = extracted.get("extracted_structured_data", {}) if isinstance(extracted.get("extracted_structured_data"), dict) else {}
    if not data:
        return _paragraph("Extraction preview not available.")
    rows: list[tuple[str, object]] = []
    for doc_type, block in list(data.items())[:20]:
        count = block.get("record_count", 0) if isinstance(block, dict) else 0
        rows.append((str(doc_type).replace("_", " ").title(), f"{count} structured records"))
    return _render_kv_table(rows)


def _render_triangulated_insights(triangulated: dict[str, Any]) -> str:
    insights = triangulated.get("insights", []) if isinstance(triangulated.get("insights"), list) else []
    if not insights:
        return _paragraph("No triangulated cross-signal insights were generated.")
    out = [r"\begin{itemize}"]
    for item in insights[:10]:
        theme = escape_latex(item.get("theme", "theme"))
        sev = escape_latex(item.get("severity", "moderate"))
        txt = escape_latex(item.get("insight", ""))
        out.append(rf"\item \textbf{{{theme}}} ({sev}): {txt}")
    out.append(r"\end{itemize}")
    return "\n".join(out) + "\n"


def _render_swot(swot: dict[str, Any]) -> str:
    if not swot:
        return _paragraph("SWOT analysis not available.")
    parts = []
    for key in ["strengths", "weaknesses", "opportunities", "threats"]:
        vals = swot.get(key, [])
        if not isinstance(vals, list) or not vals:
            vals = ["No material points recorded."]
        section = [rf"\textbf{{{escape_latex(key.title())}}}"]
        section.append(r"\begin{itemize}")
        for v in vals[:8]:
            section.append(rf"\item {escape_latex(v)}")
        section.append(r"\end{itemize}")
        parts.append("\n".join(section))
    return "\n".join(parts) + "\n"


def render_cam_payload_to_latex(payload: dict[str, Any]) -> str:
    """Render structured CAM payload to a full LaTeX document string."""
    sections: list[str] = []
    meta = payload.get("metadata", {}) if isinstance(payload.get("metadata"), dict) else {}
    entity = meta.get("entity_profile", {}) if isinstance(meta.get("entity_profile"), dict) else {}
    classification = meta.get("classification_summary", {}) if isinstance(meta.get("classification_summary"), dict) else {}
    schema_map = meta.get("schema_mapping", {}) if isinstance(meta.get("schema_mapping"), dict) else {}
    extracted = meta.get("extracted_structured_data", {}) if isinstance(meta.get("extracted_structured_data"), dict) else {}
    triangulated = meta.get("triangulated_insights", {}) if isinstance(meta.get("triangulated_insights"), dict) else {}
    swot = meta.get("swot_analysis", {}) if isinstance(meta.get("swot_analysis"), dict) else {}

    sections.append(r"\section*{Executive Summary}" + "\n" + _paragraph(payload.get("executive_summary", "")))
    sections.append(r"\section*{Company Overview}" + "\n" + _paragraph(payload.get("company_overview", "")))
    if entity:
        sections.append(r"\section*{Loan Request Summary}")
        sections.append(
            _render_kv_table(
                [
                    ("CIN", entity.get("cin", "NA")),
                    ("PAN", entity.get("pan", "NA")),
                    ("Sector", entity.get("sector", "NA")),
                    ("Subsector", entity.get("subsector", "NA")),
                    ("Loan Type", entity.get("loan_type", "NA")),
                    ("Requested Amount", _fmt_crore(entity.get("loan_amount"))),
                    ("Requested Tenure", f"{entity.get('loan_tenure_months', 'NA')} months"),
                    ("Requested Interest Rate", _fmt_pct(entity.get("interest_rate"))),
                ]
            )
        )
    if classification:
        files = classification.get("files", []) if isinstance(classification.get("files"), list) else []
        approved = sum(1 for f in files if f.get("approved"))
        sections.append(r"\section*{Classification Summary}")
        sections.append(
            _render_kv_table(
                [
                    ("Total files classified", len(files)),
                    ("Approved by analyst", approved),
                    ("Last generated at", classification.get("generated_at", "NA")),
                ]
            )
        )
    if schema_map:
        sections.append(r"\section*{Schema Mapping Summary}" + "\n" + _render_schema_mapping(schema_map))
    if extracted:
        sections.append(r"\section*{Extraction Summary}" + "\n" + _render_extraction_summary(extracted))

    fp = payload.get("financial_performance", {})
    sections.append(r"\section*{5-Year Financial Performance}" + "\n" + _paragraph(fp.get("narrative", "")))
    sections.append(r"\subsection*{Financial Ratio Table (INR Crores)}" + "\n" + _render_table(fp.get("table", {})))
    sections.append(r"\section*{Financial Trend Analysis}" + "\n" + _paragraph(payload.get("financial_trend_analysis", "")))
    sections.append(r"\section*{Liquidity and Leverage Assessment}" + "\n" + _paragraph(payload.get("liquidity_leverage_assessment", "")))

    sections.append(
        r"\section*{Promoter and Management Assessment}"
        + "\n"
        + _paragraph(payload.get("promoter_management_assessment", payload.get("promoter_analysis", "")))
    )
    sections.append(r"\section*{Industry and Sector Outlook}" + "\n" + _paragraph(payload.get("industry_sector_outlook", payload.get("industry_outlook", ""))))
    sections.append(r"\section*{Litigation Assessment}" + "\n" + _paragraph(payload.get("litigation_assessment", payload.get("litigation_profile", ""))))

    sections.append(r"\section*{Risk Flags}" + "\n" + _render_risk_flags(payload.get("risk_flags", [])))
    if triangulated:
        sections.append(r"\section*{Triangulated Insights}" + "\n" + _render_triangulated_insights(triangulated))
    if swot:
        sections.append(r"\section*{SWOT Analysis}" + "\n" + _render_swot(swot))
    sections.append(r"\section*{Decision Rationale}" + "\n" + _paragraph(payload.get("decision_logic", "")))
    sections.append(
        r"\section*{Conditions and Covenants}"
        + "\n"
        + _paragraph(payload.get("conditions_and_covenants", ""))
        + _render_conditions(payload.get("key_conditions", []))
    )
    sections.append(r"\section*{Final Recommendation}" + "\n" + _paragraph(payload.get("final_recommendation", "")))

    summary_table = {
        "headers": ["Key Output", "Value"],
        "rows": [
            ["Final Credit Score", payload.get("final_credit_score", "")],
            ["Requested Amount Evaluation", f"INR {payload.get('recommended_loan_limit_crore', '')} Crores (evaluated request)"],
            ["Final Interest Rate", f"{payload.get('interest_rate_percent', '')}% per annum"],
        ],
    }
    sections.append(r"\section*{Final Recommendation Summary}" + "\n" + _render_table(summary_table))

    sections.append(r"\section*{Supporting Evidence}" + "\n" + _render_evidence(payload.get("supporting_evidence", [])))

    template = get_latex_template()
    return (
        template.replace("{TITLE}", escape_latex(payload.get("title", "Credit Appraisal Memo")))
        .replace("{COMPANY\\_NAME}", escape_latex(payload.get("company_name", "")))
        .replace("{REPORTING\\_NOTE}", escape_latex(payload.get("reporting_note", "")))
        .replace("{CONTENT}", "\n".join(sections))
    )
