"""Triangulation + SWOT layer for compliance-oriented underwriting summaries."""

from __future__ import annotations

from typing import Any


def _f(x: object, default: float = 0.0) -> float:
    try:
        return float(x)
    except Exception:
        return default


def build_triangulated_insights(
    financials: dict[str, Any],
    features: dict[str, Any],
    research: dict[str, Any],
    extracted_structured_data: dict[str, Any] | None,
    officer_inputs: dict[str, Any],
) -> dict[str, Any]:
    """Join extracted/internal/external/officer signals into explainable insight cards."""
    extracted_structured_data = extracted_structured_data or {}

    sector = str(research.get("sector_risk", "moderate")).lower()
    lit = _f(research.get("litigation_risk_score"), 0.0)
    mgmt = _f(features.get("management_risk_score"), 0.0)
    debt_to_ebitda = _f(features.get("debt_to_ebitda"), 0.0)
    cash_stability = _f(features.get("cashflow_stability"), 50.0)

    insights: list[dict[str, Any]] = []

    if debt_to_ebitda >= 4.0 and sector in {"moderate", "high"}:
        insights.append(
            {
                "theme": "Refinancing Risk",
                "severity": "high",
                "insight": "Borrowing profile concentration combined with sector headwinds raises refinancing risk.",
            }
        )
    elif debt_to_ebitda > 2.5:
        insights.append(
            {
                "theme": "Leverage Watch",
                "severity": "medium",
                "insight": "Borrowing profile suggests moderate leverage pressure; monitor maturity ladder and rollover dependence.",
            }
        )

    if lit >= 60 or mgmt >= 60:
        insights.append(
            {
                "theme": "Governance Overlay",
                "severity": "high" if max(lit, mgmt) >= 70 else "medium",
                "insight": "Shareholding concentration plus promoter/legal indicators increase governance risk.",
            }
        )

    if cash_stability < 40:
        insights.append(
            {
                "theme": "Liquidity Stress",
                "severity": "high",
                "insight": "ALM gaps with weak cashflow stability indicate potential liquidity stress in adverse cycles.",
            }
        )
    elif cash_stability >= 65 and lit < 50:
        insights.append(
            {
                "theme": "Offsetting Strength",
                "severity": "low",
                "insight": "Strong financial momentum and stable cashflow partially offset moderate external/legal concerns.",
            }
        )

    if _f(officer_inputs.get("supply_chain_risk"), 0.0) > 0.65:
        insights.append(
            {
                "theme": "Operational Fragility",
                "severity": "medium",
                "insight": "Officer-supplied supply-chain observations indicate elevated execution risk.",
            }
        )

    return {
        "summary": f"{len(insights)} triangulated insights generated by combining extracted data, research intelligence, and officer inputs.",
        "insights": insights,
        "signal_snapshot": {
            "debt_to_ebitda": round(debt_to_ebitda, 4),
            "cashflow_stability": round(cash_stability, 2),
            "litigation_risk_score": round(lit, 2),
            "management_risk_score": round(mgmt, 2),
            "sector_risk": sector,
            "extracted_categories": sorted(list((extracted_structured_data.get("extracted_structured_data") or {}).keys())),
        },
    }


def build_swot_analysis(
    financials: dict[str, Any],
    features: dict[str, Any],
    research: dict[str, Any],
    triangulated: dict[str, Any],
    officer_inputs: dict[str, Any],
) -> dict[str, Any]:
    """Generate lightweight SWOT from joined signals."""
    strengths: list[str] = []
    weaknesses: list[str] = []
    opportunities: list[str] = []
    threats: list[str] = []

    if _f(features.get("profit_margin"), 0.0) > 0.08:
        strengths.append("Profitability profile remains healthy relative to underwriting thresholds.")
    if _f(features.get("cashflow_stability"), 0.0) >= 60:
        strengths.append("Cashflow behaviour appears stable across observed periods.")
    if _f(research.get("news_sentiment_score"), 50.0) >= 55:
        strengths.append("External sentiment is broadly supportive with limited reputational drag.")

    if _f(features.get("debt_to_equity"), 0.0) > 1.2:
        weaknesses.append("Leverage remains elevated and may constrain additional debt capacity.")
    if _f(research.get("litigation_risk_score"), 0.0) >= 55:
        weaknesses.append("Legal exposure remains a material underwriting weakness.")
    if _f(officer_inputs.get("inventory_build_up"), 0.0) > 0.6:
        weaknesses.append("Field inputs indicate inventory build-up risk and slower monetization.")

    opportunities.append("Structured covenants and staged disbursement can improve risk-adjusted lending outcomes.")
    opportunities.append("Improved operating efficiency can support stronger debt-service metrics.")

    if str(research.get("sector_risk", "moderate")).lower() in {"moderate", "high"}:
        threats.append("Sector headwinds may pressure growth, collections, and refinancing options.")
    if any(i.get("severity") == "high" for i in triangulated.get("insights", [])):
        threats.append("Triangulated high-severity risk themes require tighter monitoring and covenants.")
    if _f(officer_inputs.get("supply_chain_risk"), 0.0) > 0.65:
        threats.append("Supply-chain disruptions can trigger margin compression and working-capital stress.")

    return {
        "strengths": strengths or ["Financial and qualitative strengths are present but require more uploaded evidence for deeper validation."],
        "weaknesses": weaknesses or ["No dominant internal weakness identified from currently available documents."],
        "opportunities": opportunities,
        "threats": threats or ["External threats appear manageable under base-case assumptions."],
    }

